//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kchalupa.Web.HeartMedicalCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentPatientHistory
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public bool AllowTextContact { get; set; }
        public System.DateTime PatientBirthDate { get; set; }
        public bool IsNewPatient { get; set; }
        public string InsuranceProvider { get; set; }
        public string MemberNumber { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string ReasonForAppointment { get; set; }
        public string Conditions { get; set; }
        public string Medications { get; set; }
        public string Allergies { get; set; }
        public string Physicians { get; set; }
    }
}
